version: '3'

services:
  app:
    image: php:8.1.3-buster
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app_net
    tty: true

  composer:
    image: composer:2
    volumes:
      - .:/app
    working_dir: /app
    command: install
    networks:
      - app_net
    tty: true

networks:
  app_net:
